# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PJPChanger(object):
    def setupUi(self, PJPChanger):
        PJPChanger.setObjectName("PJPChanger")
        PJPChanger.resize(361, 390)
        PJPChanger.setMinimumSize(QtCore.QSize(361, 390))
        PJPChanger.setMaximumSize(QtCore.QSize(361, 390))
        self.centralwidget = QtWidgets.QWidget(PJPChanger)
        self.centralwidget.setObjectName("centralwidget")
        self.gbXC = QtWidgets.QGroupBox(self.centralwidget)
        self.gbXC.setGeometry(QtCore.QRect(10, 250, 341, 61))
        self.gbXC.setStyleSheet("")
        self.gbXC.setObjectName("gbXC")
        self.cbXC = QtWidgets.QComboBox(self.gbXC)
        self.cbXC.setEnabled(False)
        self.cbXC.setGeometry(QtCore.QRect(20, 23, 241, 22))
        self.cbXC.setMaximumSize(QtCore.QSize(341, 233))
        self.cbXC.setObjectName("cbXC")
        self.ckXC = QtWidgets.QCheckBox(self.gbXC)
        self.ckXC.setEnabled(False)
        self.ckXC.setGeometry(QtCore.QRect(285, 25, 70, 17))
        self.ckXC.setObjectName("ckXC")
        self.gbDC = QtWidgets.QGroupBox(self.centralwidget)
        self.gbDC.setGeometry(QtCore.QRect(10, 179, 341, 61))
        self.gbDC.setObjectName("gbDC")
        self.cbDC = QtWidgets.QComboBox(self.gbDC)
        self.cbDC.setEnabled(False)
        self.cbDC.setGeometry(QtCore.QRect(20, 23, 241, 22))
        self.cbDC.setMaximumSize(QtCore.QSize(341, 233))
        self.cbDC.setObjectName("cbDC")
        self.ckDC = QtWidgets.QCheckBox(self.gbDC)
        self.ckDC.setEnabled(False)
        self.ckDC.setGeometry(QtCore.QRect(285, 25, 70, 17))
        self.ckDC.setObjectName("ckDC")
        self.btSave = QtWidgets.QPushButton(self.centralwidget)
        self.btSave.setGeometry(QtCore.QRect(100, 333, 161, 31))
        self.btSave.setObjectName("btSave")
        self.edFile = QtWidgets.QLineEdit(self.centralwidget)
        self.edFile.setEnabled(False)
        self.edFile.setGeometry(QtCore.QRect(10, 10, 251, 22))
        self.edFile.setFrame(True)
        self.edFile.setReadOnly(True)
        self.edFile.setObjectName("edFile")
        self.gbHCF = QtWidgets.QGroupBox(self.centralwidget)
        self.gbHCF.setGeometry(QtCore.QRect(10, 40, 341, 61))
        self.gbHCF.setObjectName("gbHCF")
        self.cbHCF = QtWidgets.QComboBox(self.gbHCF)
        self.cbHCF.setEnabled(False)
        self.cbHCF.setGeometry(QtCore.QRect(20, 23, 241, 22))
        self.cbHCF.setCurrentText("")
        self.cbHCF.setObjectName("cbHCF")
        self.ckHCF = QtWidgets.QCheckBox(self.gbHCF)
        self.ckHCF.setEnabled(False)
        self.ckHCF.setGeometry(QtCore.QRect(285, 25, 70, 17))
        self.ckHCF.setObjectName("ckHCF")
        self.lbPath = QtWidgets.QLabel(self.centralwidget)
        self.lbPath.setGeometry(QtCore.QRect(10, 320, 55, 16))
        self.lbPath.setObjectName("lbPath")
        self.gbPC = QtWidgets.QGroupBox(self.centralwidget)
        self.gbPC.setGeometry(QtCore.QRect(10, 110, 341, 61))
        self.gbPC.setObjectName("gbPC")
        self.cbPC = QtWidgets.QComboBox(self.gbPC)
        self.cbPC.setEnabled(False)
        self.cbPC.setGeometry(QtCore.QRect(20, 23, 241, 22))
        self.cbPC.setMaximumSize(QtCore.QSize(341, 233))
        self.cbPC.setObjectName("cbPC")
        self.ckPC = QtWidgets.QCheckBox(self.gbPC)
        self.ckPC.setEnabled(False)
        self.ckPC.setGeometry(QtCore.QRect(285, 25, 70, 17))
        self.ckPC.setObjectName("ckPC")
        self.btOpen = QtWidgets.QPushButton(self.centralwidget)
        self.btOpen.setGeometry(QtCore.QRect(270, 10, 81, 22))
        self.btOpen.setObjectName("btOpen")
        PJPChanger.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PJPChanger)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 361, 21))
        self.menubar.setObjectName("menubar")
        PJPChanger.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PJPChanger)
        self.statusbar.setMinimumSize(QtCore.QSize(361, 0))
        self.statusbar.setMaximumSize(QtCore.QSize(361, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.statusbar.setFont(font)
        self.statusbar.setAutoFillBackground(True)
        self.statusbar.setStyleSheet("color: #a5a5a5;")
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        PJPChanger.setStatusBar(self.statusbar)

        self.retranslateUi(PJPChanger)
        QtCore.QMetaObject.connectSlotsByName(PJPChanger)

    def retranslateUi(self, PJPChanger):
        _translate = QtCore.QCoreApplication.translate
        PJPChanger.setWindowTitle(_translate("PJPChanger", "PJP Changer"))
        self.gbXC.setTitle(_translate("PJPChanger", "N/A"))
        self.ckXC.setText(_translate("PJPChanger", "N/A"))
        self.gbDC.setTitle(_translate("PJPChanger", "N/A"))
        self.ckDC.setText(_translate("PJPChanger", "N/A"))
        self.btSave.setText(_translate("PJPChanger", "Save Changes"))
        self.gbHCF.setTitle(_translate("PJPChanger", "Select Salesman HCF"))
        self.ckHCF.setText(_translate("PJPChanger", "HCF"))
        self.lbPath.setText(_translate("PJPChanger", "TextLabel"))
        self.gbPC.setTitle(_translate("PJPChanger", "Select Salesman PC"))
        self.ckPC.setText(_translate("PJPChanger", "PC"))
        self.btOpen.setText(_translate("PJPChanger", "Open"))

import res_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PJPChanger = QtWidgets.QMainWindow()
    ui = Ui_PJPChanger()
    ui.setupUi(PJPChanger)
    PJPChanger.show()
    sys.exit(app.exec_())

