SELECT p.PJP, p.DSR, p.LDESC as SalesName, a.LDESC as CategoryName
FROM PJP_HEAD p
INNER JOIN SELLING_CATEGORY a on a.SELL_CATEGORY = p.SELL_CATEGORY
INNER JOIN DSR ds on ds.DSR = p.DSR
WHERE a.SELL_CATEGORY = 103 and ds.JOB_TYPE = 01 and p.ACTIVE = 1


SELECT p.PJP, p.DSR, p.LDESC as SalesName, a.LDESC as CategoryName
FROM PJP_HEAD p
INNER JOIN SELLING_CATEGORY a on a.SELL_CATEGORY = p.SELL_CATEGORY
INNER JOIN DSR ds on ds.DSR = p.DSR
WHERE a.SELL_CATEGORY = 102 and ds.JOB_TYPE = 01 and p.ACTIVE = 1


SELECT SKU, SELL_CATEGORY, COUNT(SKU) AS NumberOfDuplicate
FROM SKU_CATEGORY
INNER JOIN
WHERE SELL_CATEGORY=101
GROUP BY SKU, SELL_CATEGORY
ORDER BY NumberOfDuplicate ASC


select * from IG_O_SalesOrderHeader where Comments='PO-TEST13'


select * from CASHMEMO_DETAIL where DOC_NO in (
'18S005010650'
)


SELECT p.PJP, p.DSR, p.LDESC as SalesName, a.LDESC as CategoryName
FROM PJP_HEAD p
INNER JOIN SELLING_CATEGORY a on a.SELL_CATEGORY = p.SELL_CATEGORY
INNER JOIN DSR ds on ds.DSR = p.DSR
WHERE a.SELL_CATEGORY = 103 and ds.JOB_TYPE = 01 and p.ACTIVE = 1


SELECT a.SKU, c.LDESC, p.SELL_CATEGORY, p.SDESC
FROM SELLING_CATEGORY p
INNER JOIN SKU_CATEGORY a on a.SELL_CATEGORY = p.SELL_CATEGORY
INNER JOIN SKU c on c.SKU = a.SKU
WHERE a.SKU in ('20072129', '67332054', '20206133', '62071796')
ORDER BY 'LDESC' ASC


SELECT * FROM SKU
